### ISSUE TITLE
Missing a complete dashboard with vanilla components

### ISSUE THREAD

**Issue by zaryftech** [flavorly/vanilla-components#103]
Vanilla Component is amazing but some core elements is missing on it.
We are building an SAAS project with vanilla components. We required to use thirt party dashboard from github called "KUI Dashboard".

A lot of problems we are facing. Both packages has dedicated same components.

Could we expected a dashboard, sidebar and charts officially?

**Comment by nikuscs** [comment]
Hello and thank you for using Vanilla <3 much appriciated! 

Im not really sure what you mean my a full dashboard, but i use vanilla to create my own saas and dashboards, nothing should stop you from doing it. If your question is if we will ever make some sort of boilerplate to show off usage of the components, i dont have the time right now for it but i accept PRs.

Regarding charts, i dont feel like implemenenting or writtinf charts from scratch, what we can do is wrap something like apexcharts or chartjs that already include everything that is needed. :)

If any special components your missing please feel free to suggest. Currntly we are aiming for a next release based on Radix Vue, lets see how it goes.
