### ISSUE TITLE
default placeholder for VanillaInput is "text" which should've been empty according to documentation

### ISSUE THREAD

**Issue by tauhid8k** [flavorly/vanilla-components#106]
If I don't want any placeholder by default for input it's not possible without using an empty placeholder. Or maybe I am missing something.

**Comment by nikuscs** [comment]
I guess undefined should do the job, but im gonna check this tomorow and give an update here! thanks for spotting it :p

**Comment by nikuscs** [comment]
@tauhid8k The default placeholder has been changed to empty, and it should accept empty on v0.7.60, please kindly upgrade and thanks for pointing out!
