### ISSUE TITLE
PhoneInput and CountryInput v-model issue 

### ISSUE THREAD

**Issue by dd3v** [flavorly/vanilla-components#117]
Hello @nikuscs and thank you for the Vanilla Components!

There is probably a bug with the PhoneInput component. Reactivity doesn't work when I pass a variable to v-model and change its value.

```
<script setup>
import { PhoneInput } from '@flavorly/vanilla-components'
import { ref } from 'vue'

const number = ref('+35191523813')
const valueCountry = 'PT'


const submit = () => {
    number.value = '+35191521111';
};

</script>
```

```
<template>
    <PhoneInput
      v-model="number"
      :country-code="valueCountry"
      feedback="Im useful helper out here, choose wisely"
      :favorite-countries="['PT', 'ES', 'US']"
      country-placeholder="Pick your phone country"
      phone-placeholder="National Number"
    />
</template>
```

I didn't catch that, but it works with an array :) 

```
const number = ref(['+35191523813'])
const valueCountry = 'PT'

const submit = () => {
    number.value[0] = '+35191521111';
};

```

**Comment by dd3v** [comment]
Exact same issue with CountryInput. The component doesn't respond to updates for the 'country' property.

`<CountryInput v-model="country" name="country" :favorite-countries="['US', 'GB']" placeholder="Country" />`

**Comment by nikuscs** [comment]
Thanks for report, im gonna test this tomorow, did you used the docs playground to test this?

**Comment by dd3v** [comment]
Thank you! No, I did not use docs playground.

**Comment by dd3v** [comment]
@nikuscs 

Here is one more issue. it seems like the CountryInput is not initializing fast enough before receiving the v-model. 


```
<template>
  <CountryInput v-model="profile.country" name="country" :favorite-countries="['US', 'GB']" placeholder="Country" />
</template>
<script setup>
import { reactive, onMounted } from 'vue';
import { CountryInput } from '@flavorly/vanilla-components';

const profile = reactive({
  country: 'PL',
});

onMounted(() => {
  // error -  Unhandled error during execution of scheduler flush.
  profile.country = 'US';

  // works fine
  setTimeout(() => { profile.country = 'GB'; }, 300);
});
</script>
```

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.#130

**Comment by nikuscs** [comment]
I accept a PR if you are willing to do so, the library is on maintenance mode for now.
