### ISSUE TITLE
Question: If clearable is true, selectorIcon is not shown. How to keep both?

### ISSUE THREAD

**Issue by Emuzex** [flavorly/vanilla-components#118]
I want to show selectorIcon when nothing selected, then if user select something use clearable icon.

**Comment by nikuscs** [comment]
In my opinion it does not make sense to keep both, either the select is not yet filled, its a bit weird UX to have both icons, but whats your use case exactly? I can accept a PR if you are willing to drop it :p

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.#103
