### ISSUE TITLE
Question: how can I modify the nested Input attributes of 'DateTimeInput'?

### ISSUE THREAD

**Issue by peter-fan-cn** [flavorly/vanilla-components#124]
I need change the font size of the input box of 'DateTimeInput' element, how can I do it?
I can see there is a `inputProps` in the base props, but it do nothing.

**Comment by peter-fan-cn** [comment]
``` jsx
<DateTimeInput
                        v-model="parameter.date"
                        is-required
                        :inline="false"
                        color="amber"
                        :options="{color:'amber'}"
                        mode="date"
                        placeholder="Please select your date"
                        :input-props="{classes:{wrapper:'text-xs'}}"
                    />
```

**Comment by nikuscs** [comment]
You can use classes directly to modify the appearance of the underlying input, you can also free to slot the default slot and bring your own VanillaInput with your own variant/styles

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.#130
