### ISSUE TITLE
feat: Figma Kit

### ISSUE THREAD

**Issue by ennioVisco** [flavorly/vanilla-components#126]
Hello, I love your kit, is so simple and clear. 
Did you ever consider developing a Figma UI Kit? I believe this would boost adoption since it would be much easier to use by designers!

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.#130

**Comment by nikuscs** [comment]
Not yet, most of this is based on Tailwind UI styles with a little bit of my taste just for the shadows and what not, but im open to accept a Figma Kit indeed :)

**Comment by nikuscs** [comment]
I accept a PR if you are willing to do so, the library is on maintenance mode for now.
