### ISSUE TITLE
Disabled phone input 

### ISSUE THREAD

**Issue by fwta-dev** [flavorly/vanilla-components#128]
Question : 
I have disabled phone input props . but do nothing . how to Disabled it ?

**Comment by Ale6333499** [comment]
Could you please tell me what are the steps of your installation process? Mine has no style.#130

**Comment by nikuscs** [comment]
You should be able to pass in "disabled" to the input as true, and it should disable both, if not please let me know and ill push a PR with it.

**Comment by nikuscs** [comment]
I accept a PR if you are willing to do so, the library is on maintenance mode for now.
