### ISSUE TITLE
After downloading using the following steps, the component has no style

### ISSUE THREAD

**Issue by Ale6333499** [flavorly/vanilla-components#130]
![image](https://github.com/flavorly/vanilla-components/assets/113077418/167b0bbd-e3d0-4121-8fbe-985892cd6763)

**Comment by Ale6333499** [comment]
![image](https://github.com/flavorly/vanilla-components/assets/113077418/00f1dbca-f9af-4906-bb15-732973f3fc70)

**Comment by eduardoleal** [comment]
If you are using tailwind make sure to update tailwind.config.js: https://vanilla-components.com/guide/quick-start.html#using-tailwind

**Comment by Ale6333499** [comment]
> 如果您使用 tailwind，请确保更新 tailwind.config.js：https://vanilla-components.com/guide/quick-start.html#using-tailwind
thanks

**Comment by nikuscs** [comment]
Yeah like @eduardoleal replied you need to ensure to add the presets to your tailwind config! Im closing this day, please make sure next time to not spam other issues with it.

Closing this as its fixed
