### ISSUE TITLE
RichSelect fetchEndpoint: URLs without hostname do not work

### ISSUE THREAD

**Issue by DomiStyle** [flavorly/vanilla-components#132]
When using RichSelect with a URL that does not contain a hostname the query parameters will not be added to the request.

For example:

`fetchEndpoint="http://localhost/api/options"` will correctly request `http://localhost/api/options?query=test&page=1`
`fetchEndpoint="/api/options"` will always request `http://localhost/api/options` without any query parameters.

The documentation mentions that a FQDN should be used but it probably shouldn't fail in this fashion.

**Comment by nikuscs** [comment]
I accept a PR if you are willing to do so, the library is on maintenance mode for now.
