### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by frederikhors** [flavorly/vanilla-components#37]
Your work is amazing!

What do you think about creating this for Svelte too?

**Comment by nikuscs** [comment]
Hey @frederikhors ! Thanks a lot! For the moment im focused on Vue, as its my main stack, and even with vue let alone its a lot of work :p i wanted to keep library short so i can keep maintaining it for a long time, i have 0 expirience with Svelt, so i dont really have plans for now :(

But in case your are motivated enough, i can surely help you out along the lines! 👯

**Comment by basarozcan** [comment]
Another thanks from my side! Your components are masterpiece!

**Comment by FilipeBorges1993** [comment]
Amazing work, @nikuscs  
A big thanks from my side too
