### ISSUE TITLE
RichSelect fetch-endpoint set selected

### ISSUE THREAD

**Issue by mferenc79** [flavorly/vanilla-components#76]
Hi, amazing project.
RichSelect default value is loaded but not selected.
Can you help me what I did wrong?

                    <RichSelect
                        v-model="zipId"
                        :fetch-endpoint="testUrl"
                        value-attribute="id"
                        text-attribute="name"
                        :minimum-input-length="3"
                    >

                    </RichSelect>

Route::get('/fetch-users', function(Request $request){
       return ResolveRichSelectOptions::for(User::class, ['name', 'id']);
})->middleware('web')->name('api.fetch-users');

**Comment by nikuscs** [comment]
Are you sure that your zipId is the same value as the its being returned on the v-model ? Also String or Number. Please be sure about this, i will test again today and can guide on this issue in case your are unable to figure it out.

**Comment by mferenc79** [comment]
it is true that zipId is STRING and the value returned by v-model is a INT, but if zipId is INT, then there is no return value

**Comment by nikuscs** [comment]
If this issue is resolved @mferenc79 feel free to re-open it!
