### ISSUE TITLE
Switch popper.js to Floating UI

### ISSUE THREAD

**Issue by binaryfire** [flavorly/vanilla-components#95]
Hey @nikuscs 

It would be good to switch popper.js for Floating UI: [https://github.com/floating-ui/floating-ui](https://github.com/floating-ui/floating-ui). Floating UI is developed by the same devs and is the replacement for Popper. They're recommending everyone migrate, since Popper will only be getting fixes from now on.

Migration guide: [https://floating-ui.com/docs/migration](https://floating-ui.com/docs/migration)

**Comment by nikuscs** [comment]
@binaryfire Thanks for your comment! We are def. planning to switch over to floating UI on the next major release, this will include a a bit of a hard-refactor and popperjs will be dropped in favor of FloatingUI indeed :)

**Comment by nikuscs** [comment]
This was moved to the project: https://github.com/orgs/flavorly/projects/1 close in favor of it!
