### ISSUE TITLE
Slider component suggestions

### ISSUE THREAD

**Issue by binaryfire** [flavorly/vanilla-components#96]
Hey @nikuscs 

Nice work with Vanilla Components! Do you have an ETA on the slider? That's the only thing stopping us from switching to this library (and we'd love to switch over ASAP...).

This could be a good code reference: [https://github.com/vueform/slider](https://github.com/vueform/slider). It's based on [https://github.com/leongersen/noUiSlider](https://github.com/leongersen/noUiSlider)

**Comment by nikuscs** [comment]
@binaryfire Thanks for the suggestion, we wont be adding new components ( unless you want to PR ) until the next refactor the core, keep in mind you a free to push this component into your app using the vanilla styling & system : 

Please follow the guide on : https://vanilla-components.com/guide/advanced-configuration.html

Once your have a clean implementation on your side feel free to share with me and i might add it, right now im only adding components i find need into, hope you understand :p, PRs are welcome!

**Comment by binaryfire** [comment]
@nikuscs No problems, totally understand. I'm more of backend (Laravel) dev so unfortunately my Vue skills aren't great. I'll check out the advanced configuration docs for now.

**Comment by nikuscs** [comment]
This was moved to the project: https://github.com/orgs/flavorly/projects/1 close in favor of it!
