### ISSUE TITLE
How to refresh DataTable manually?

### ISSUE THREAD

**Issue by dd3v** [flavorly/vanilla-components#99]
Hi @nikuscs 

Thanks for Vanilla Components!  Is there a way to invoke the refresh function in the Datatable using 'ref' or any other method? 
For example, if I need to invoke the fetchData function after a specific event.

**Comment by nikuscs** [comment]
Hello @dd3v, thanks! :)

Surely its possible, just tagged a new version that exposes the following methods : 

`defineExpose({
  fetchData,
  resetUrl,
  resetAllSettings,
  resetSorting,
  resetAction,
  resetSearchQuery,
  resetFiltersAndSearch,
  poolForever,
  refresh,
  poolUntil,
  deselectAllItemsInPage,
  selectItem,
  deselectAllItems,
  toggleSelectAll,
  isItemSelected,
  executeAction,
  currentAction,
  isFetching,
  datatable,
})`

Please update to **0.7.57**
